CREATE TABLE `electeur` (
	`idElecteur` VARCHAR(200) NOT NULL DEFAULT '',
	`Nom` VARCHAR(45) NOT NULL,
	`Prenom` VARCHAR(45) NOT NULL,
	`Commune` VARCHAR(45) NOT NULL,
	`CarteID` VARCHAR(45) NOT NULL,
	`SecuID` VARCHAR(45) NOT NULL,
	`Code` VARCHAR(200) NOT NULL,
	`CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`idElecteur`),
	INDEX `Code` (`Code`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `actions` (
	`idAction` INT(11) NOT NULL AUTO_INCREMENT,
	`Type` VARCHAR(45) NULL DEFAULT NULL,
	`Statut` VARCHAR(45) NULL DEFAULT NULL,
	`Erreur` VARCHAR(100) NULL DEFAULT NULL,
	`idElecteur` VARCHAR(200) NULL DEFAULT NULL,
	`actionDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`idAction`),
	INDEX `FK_idElecteur` (`idElecteur`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=167
;


CREATE TABLE `vote` (
	`voteId` INT(11) NOT NULL AUTO_INCREMENT,
	`voterId` VARCHAR(200) NOT NULL,
	`voteDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`optionVote` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`voteId`),
	INDEX `FK_vi` (`voterId`),
	CONSTRAINT `FK_vi` FOREIGN KEY (`voterId`) REFERENCES `electeur` (`idElecteur`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=24
;

